## 6.86x Homework 1

## Part 1

$x^{(1)} = (-1, -1)$

$x^{(2)} = (1, 0)$

$x^{(3)} = (-1, 1.5)$

### Perceptron algorithm

### Import packages

In [2]:
import numpy as np
import matplotlib.pyplot as plt

- Initialize training points

In [78]:
x = np.array([[-1, -1], [1, 0], [-1, 10]])

- Printing the training points

In [79]:
print(x)

[[-1 -1]
 [ 1  0]
 [-1 10]]


- Printing *a* point, not forgetting about zero-indexing

In [73]:
print(x[1])

[1 0]


- Initialize labels

In [74]:
y = np.array([[1], [-1], [1]])
print(y)

[[ 1]
 [-1]
 [ 1]]


In [7]:
print(y[1])

[-1]


In [34]:
n = 3
m = 5

In [30]:
ind = list(range(0, n, 1))
print(ind)

[0, 1, 2]


In [35]:
ind2 = np.array(range(0, m, 1))
print(ind2)

[0 1 2 3 4]


In [24]:
type(ind)

list

### Recall the Perceptron algorithm
$\theta = (0, 0)'$

for i = 0, 1, 2 do

$y^{(i)}(\theta \cdot x^{(i)}) \le 0$

$\theta = \theta + y^{(i)}x^{(i)}$

Below is how to do dot product in Numpy

In [31]:
np.dot(x[0], x[1])

-1.0

In [61]:
theta = np.array([0, 0])
print(theta)

[0 0]


- Function useful in the main code

In [97]:
foo = np.zeros((3, 2))
print(foo)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [98]:
for i in np.array([0, 1, 2]):
    foo[i] = np.array([i + 3, i + 5]) + foo[i]
print(foo)

[[3. 5.]
 [4. 6.]
 [5. 7.]]


- How to append a NumPy array

In [116]:
empty_l = []
for i in np.array([0, 5, 6]):
    empty_l.append([i + 1, 2 * i])
print(empty_l)

[[1, 0], [6, 10], [7, 12]]


## Main code for part 1

In [127]:
theta = np.array([0, 0]) # Initialize theta

print(theta) # Check starting theta

classifier = np.zeros((3))
print(classifier)
it = 0 # Iteration number

sep_pln = []

mistakes = 0 # Initialize mistake count
looping_ind = np.array([1, 2, 0])
while np.min(classifier) <= 0:
    print(f'\nIteration {it + 1}:\n')
    for i in looping_ind:
        print(f'\nTraining point number {i + 1}:\n')
        print(f' Classifier value = {y[i] * np.dot(theta, x[i])}\n')
        if y[i] * np.dot(theta, x[i]) <= 0:
            theta = theta + y[i] * x[i]
            sep_pln.append([theta])
            print(f' Updated theta value: {theta}\n')
            print(f' Updated classifier value: {y[i] * np.dot(theta, x[i])}\n')
            mistakes = mistakes + 1
    for i in looping_ind:
        classifier[i] = y[i] * np.dot(theta, x[i])
        print(f'\nClassifier value for training example number {i + 1}:\n {classifier[i]}')
    it = it + 1

print(sep_pln)
    # print(f' theta: {theta}')
print(f'\nNumber of mistakes: {mistakes}\n')


[0 0]
[0. 0. 0.]

Iteration 1:


Training point number 2:

 Classifier value = [0]

 Updated theta value: [-1  0]

 Updated classifier value: [1]


Training point number 3:

 Classifier value = [1]


Training point number 1:

 Classifier value = [1]


Classifier value for training example number 2:
 1.0

Classifier value for training example number 3:
 1.0

Classifier value for training example number 1:
 1.0
[[array([-1,  0])]]

Number of mistakes: 1



## Part 2

In [132]:
theta_vec = np.array([0, 0])
theta0 = 0
# print(theta_vec)
# type(theta_vec)

Note that when we use the perceptron algorithm, one way to write the classifier is 

$$y(\theta \cdot x + \theta_{0}).$$

To use a more compact notation, let $X = (x', 1)$ and $\Theta = (\theta, \theta_{0})$. Then we can write the classifier with offset as:

$$y^{(i)} \cdot \Theta \cdot X^{(i)}$$

## Main code for part 2

In [182]:
theta = np.array([-3, 3, -3])
x = np.array([[-4, 2, 1],
             [-2, 1, 1],
             [-1, -1, 1], 
             [2, 2, 1], 
             [1, -2, 1]])
print(x)
print(x.shape)
print(x[2])
y = np.array([1, 1, -1, -1, -1])

It = 0 # Iteration number
Loop_ind = np.array(range(0, x.shape[0], 1))
print(Loop_ind)
type(Loop_ind)

mistakes = 0
sep_pln = np.array([[0, 0, 0]])
cls_col = np.zeros((5))

# while It <= k:
while np.min(cls_col) <= 0:
    print(f'Iteration {It + 1}:\n')
    for i in Loop_ind: 
        cls = y[i] * np.dot(theta, x[i]) 
        print(f' example {i + 1}:\n')
        if cls <= 0:
            mistakes = mistakes + 1
            theta = theta + y[i] * x[i]
            print(f' MISS CLASSIFICATION: {cls}\n')
            print(f' updated theta: {theta}\n')
            sep_pln = np.append(sep_pln, [theta], axis= 0)
        else: 
            print(f' correctly classified: {cls}\n')
    for i in Loop_ind:
        cls_col[i] = y[i] * np.dot(theta, x[i]) 
    It = It + 1
print(f'Total number of mistakes: {mistakes}\n') 
print(f'Theta progression: {sep_pln}\n')
    

[[-4  2  1]
 [-2  1  1]
 [-1 -1  1]
 [ 2  2  1]
 [ 1 -2  1]]
(5, 3)
[-1 -1  1]
[0 1 2 3 4]
Iteration 1:

 example 1:

 correctly classified: 15

 example 2:

 correctly classified: 6

 example 3:

 correctly classified: 3

 example 4:

 correctly classified: 3

 example 5:

 correctly classified: 12

Total number of mistakes: 0

Theta progression: [[0 0 0]]



## Part 6

- Necessary functions

In [183]:
print(np.pi)

3.141592653589793


In [187]:
np.cos(np.pi * 1 / 2)

6.123233995736766e-17

In [185]:
np.cos(0)

1.0

## Main code for part 6

d = 2, $y_{1} = y_{2} = 1$. $x^{(1)}$ first.

In [33]:
# theta = np.array([0, 0])
d = 3
theta = np.zeros((d))
ind = np.array(range(0, d, 1))
np.random.shuffle(ind)
print(f'Shuffled ind: \n{ind}\n')
# ind = np.array([])
x = np.zeros((d, d))
y = np.ones((d))
# y = np.array([1, -1, -1, -1, 1])
for i in ind:
    x[i, i] = np.cos(np.pi * (i + 1))
print(f' x: \n{x}\n')
x
print(f' y: \n{y}\n')

# loop_ind = np.array([0, 1])

cls = np.empty((d))

for i in ind:
    cls[i] = y[i] * np.dot(theta, x[i])
print(f'Classifer values: \n{cls}\n')

it = 0
mistakes = 0
sep_pln = np.array([np.zeros(d)]) 
print(sep_pln)

while np.min(cls) <= 0:
    print(f'Iteration {it + 1}\n')
    for i in ind: 
        print(f' (it = {it}) point {i + 1}\n')
        if y[i] * np.dot(theta, x[i]) <= 0:
            theta = theta + np.dot(y[i], x[i])
            print(f' MISS CLASSIFICATION\n')
            print(f' theta:\n {theta}\n')
            mistakes = mistakes + 1
            sep_pln = np.append(sep_pln, [theta], axis = 0)
    for i in ind:
        cls[i] = y[i] * np.dot(theta, x[i])
    it = it + 1
print(f'Total number of mistakes: {mistakes}\n')
print(f'Theta progression: \n{sep_pln}\n')
print(f'End classifer values: \n{cls}\n')
                  
                  

Shuffled ind: 
[0 2 1]

 x: 
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]

 y: 
[1. 1. 1.]

Classifer values: 
[0. 0. 0.]

[[0. 0. 0.]]
Iteration 1

 (it = 0) point 1

 MISS CLASSIFICATION

 theta:
 [-1.  0.  0.]

 (it = 0) point 3

 MISS CLASSIFICATION

 theta:
 [-1.  0. -1.]

 (it = 0) point 2

 MISS CLASSIFICATION

 theta:
 [-1.  1. -1.]

Total number of mistakes: 3

Theta progression: 
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [-1.  0. -1.]
 [-1.  1. -1.]]

End classifer values: 
[1. 1. 1.]

